openapi: "3.0.0"

info:
  version: "0.0. 1"
  title: Shopkart ecommerce api
  contact:
    email: "frontendweb.sg@gmail.com"
    url: "http://frontendweb.in"

servers:
  - url: http://localhost:4200/api

paths:
  /user:
    post:
      summary: Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstname:
                  type: string
      responses:
        "201":
          description: "OK"
