openapi: "3.0.0"

info:
  version: "0.0. 1"
  title: Shopkart ecommerce api
  description: Ecommerce api
  contact:
    email: "frontendweb.sg@gmail.com"
    url: "http://frontendweb.in"

servers:
  - url: http://localhost:4200/api

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /auth:
    post:
      summary: login user
      description: signin user by email and password
      requestBody:
        description: Login
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: Enter email
                password:
                  type: string
                  description: Enter password
            example:
              email: "pradeep.kumar5@rsystems.com"
              password: "Admin@123"

      responses:
        "200":
          description: Success Login
      tags:
        - "Auth"
  /auth/signup:
    post:
      summary: register user
      description: register user with role or without role
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstname:
                  type: string
                lastname:
                  type: string
                email:
                  type: string
                password:
                  type: string
                mobile:
                  type: string
                role:
                  type: array
            example:
              firstname: "Pradeep"
              lastname: "kumar"
              email: "abc@gmail.com"
              passsword: "admin@123"
              role: "user"
      responses:
        "201":
          description: User successfully created
      tags:
        - "Auth"
  /brand:
    get:
      summary: fetch brands list
      description: Fetch all brands
      parameters:
        - name: x-access-token
          in: header
          schema:
            type: string
      responses:
        "200":
          description: Json array of brands
          content:
            application/json:
              schema:
                type: array
                properties:
                  title:
                    type: string
                  slug:
                    type: string
                  active:
                    type: boolean
                  order:
                    type: number
      tags:
        - "Brand"
    post:
      summary: Brand post
      description: Add brand
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
            example:
              title:
                value: "Abc"
                summary: Add any brand

      responses:
        "201":
          description: Brand added
          content:
            application/json:
              schema:
                type: array
                properties:
                  title:
                    type: string
                  slug:
                    type: string
                  active:
                    type: boolean
                  order:
                    type: number
      tags:
        - "Brand"
  /category:
    get:
      summary: fetch categories
      description: Fetch all categories
      responses:
        "200":
          description: List category
      tags:
        - "Category"
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "201":
          description: Category added
      tags:
        - "Category"
