openapi: "3.0.0"

info:
  version: "0.0. 1"
  title: Shopkart ecommerce api
  description: Ecommerce api
  contact:
    email: "frontendweb.sg@gmail.com"
    url: "http://frontendweb.in"

servers:
  - url: http://localhost:4200/api

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /auth:
    post:
      summary: Login user
      description: signin user by email and password
      requestBody:
        description: Login
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: Enter email
                password:
                  type: string
                  description: Enter password
      responses:
        "200":
          description: Success Login
  /brand:
    get:
      summary: Returns a list of brands
      description: Get all the brands list
      parameters:
        - name: x-access-token
          in: header
          schema:
            type: string
      responses:
        "200":
          description: Json array of brands
          content:
            application/json:
              schema:
                type: array
                properties:
                  title:
                    type: string
                  slug:
                    type: string
                  active:
                    type: boolean
                  order:
                    type: number
    post:
      summary: Brand post
      description: Add brand
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
            example:
              title:
                value: "Abc"
                summary: Add any brand

      responses:
        "201":
          description: Brand added
          content:
            application/json:
              schema:
                type: array
                properties:
                  title:
                    type: string
                  slug:
                    type: string
                  active:
                    type: boolean
                  order:
                    type: number
